backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: surjithctly/neat-starter
media_folder: "src/static/img"
public_folder: "/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Site Settings"
    name: "site_settings"
    editor:
      preview: false
    files:
      - label: "Site Identity"
        name: "site_identity"
        file: "src/_data/site_identity.yaml"
        fields:
          - label: Socials
            name: socials
            widget: list
            allow_add: true
            collapsed: false
            fields:
              - { label: Url, name: url, widget: string }
              - { label: Icon, name: icon, widget: string }
  - label: "Styles"
    name: "styles"
    editor:
      preview: false
    files:
      - label: "Styles"
        name: "color_styles"
        file: "src/_data/styles.json"
        fields:
          - { label: Body, name: body, widget: color , required: false }
          - { label: Container Background, name: containerColor, widget: color , required: false }
          - { label: Primary, name: primary, widget: color , required: false }
          - { label: Secondary, name: Secondary, widget: color , required: false }
          - { label: Accent, name: accent, widget: color , required: false }
          - { label: Success, name: success, widget: color , required: false }
          - { label: Warning, name: warning, widget: color , required: false }
          - { label: Danger, name: danger, widget: color , required: false }
          - { label: Link, name: link, widget: color , required: false }
          - { label: Link Hover, name: linkHover, widget: color , required: false }
          - { label: Button Text, name: buttonText, widget: color , required: false }
          - { label: Button Background, name: buttonBackground, widget: color , required: false }
          - { label: Button Hover Text, name: buttonHoverText, widget: color , required: false }
          - { label: Button Hover Background, name: buttonHoverBackground, widget: color , required: false }
          - { label: Text, name: text, widget: color , required: false }
          - { label: h1, name: h1, widget: color , required: false }
          - { label: h2, name: h2, widget: color , required: false }
          - { label: h3, name: h3, widget: color , required: false }
          - { label: h4, name: h4, widget: color , required: false }
          - { label: h5, name: h5, widget: color , required: false }
          - { label: h6, name: h6, widget: color , required: false }
          - { label: Socials Background, name: socialsBackground, widget: color , required: false }
          - { label: SocialsColor, name: socialsColor, widget: color , required: false }
      - label: "Sizing"
        name: "sizing_styles"
        file: "src/_data/sizing.json"
        fields:
          - { label: Container Width, name: globalWidth, widget: number }
          - { label: Container padding, name: containerPadding, widget: number }
      - label: "Typography"
        name: "typography_styles"
        file: "src/_data/typography.json"
        fields:
          - { label: Link, name: link, widget: number , required: false }
          - { label: Text, name: text, widget: number , required: false }
          - { label: h1, name: h1, widget: number , required: false }
          - { label: h2, name: h2, widget: number , required: false }
          - { label: h3, name: h3, widget: number , required: false }
          - { label: h4, name: h4, widget: number , required: false }
          - { label: h5, name: h5, widget: number , required: false }
          - { label: h6, name: h6, widget: number , required: false }
  - label: "Pages"
    name: "pages"
    folder: "src/pages"
    create: true
    editor:
      preview: false
    fields:
      - {label: "Title", name: "title", widget: string}
      - {label: "Permalink", name: "permalink", widget: string}
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Caption", name: "caption", widget: "markdown" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Bottom", name: "bottom", widget: "markdown" }
  - label: "Podcasts"
    name: "podcasts"
    folder: "src/podcasts"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Video", name: "video", widget: "string"}
      - { label: "Audio", name: "audio", widget: "file"}

  - label: "Articles"
    name: "blog"
    folder: "src/posts"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        create: true
        options: [ "Tags", "created", "from", "config.yml" ]
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Meta Settings"
        name: "settings"
        file: "src/_data/settings.yaml"
        fields:
          - { label: Name, name: name, widget: string }
          - { label: Author, name: author, widget: string }
          - { label: URL, name: url, widget: string }
  - label: "Footer"
    name: "global_footer"
    editor:
      preview: false
    files:
      - label: "Footer"
        name: "footer"
        file: "src/_data/footer.yaml"
        fields:
          - { label: Logo, name: footer_logo, widget: image }
          - { label: Caption, name: footer_caption,description: '@year will be replaced by the current year', widget: string }
  - label: "Header"
    name: "global_header"
    editor:
      preview: false
    files:
      - label: "Header"
        name: "header"
        file: "src/_data/header.yaml"
        fields:
          - { label: Logo, name: header_logo, widget: image }
  - label: 'Home'
    name: home
    editor:
      preview: false
    files:
      - label: "Hero"
        name: "home_hero"
        file: "src/_data/home_hero.yaml"
        fields:
          - { label: Title, name: text, widget: string }
          - { label: Caption, name: caption, widget: markdown }
          - { label: Image, name: image, widget: image }
      - label: "CTA"
        name: "home_cta"
        file: "src/_data/home_cta.yaml"
        fields:
          - { label: Title, name: label_cta, widget: string }
          - label: CTA Links
            name: ctas
            widget: list
            allow_add: true
            collapsed: false
            fields:
              - { label: Label, name: label, widget: string }
              - { label: Url, name: url, widget: string }
      - label: "Form"
        name: "home_form"
        file: "src/_data/home_form.yaml"
        fields:
          - { label: Form Title, name: form_title, widget: string }
          - { label: Form Description, name: form_description, widget: markdown }
          - { label: Form Logo, name: form_logo, widget: image }
          - { label: Form Url, name: form_url, widget: string }
          - label: Form Links
            name: form_links
            widget: list
            allow_add: true
            collapsed: false
            fields:
              - { label: Label, name: label, widget: string }
              - { label: Url, name: url, widget: string }
              - { label: Logo, name: form_link_logo, widget: image }
      - label: "Bottom Banner"
        name: "home_bottom_banner"
        file: "src/_data/home_bottom_banner.yaml"
        fields:
          - { label: Caption, name: home_bottom_caption, widget: markdown }
  - label: 'Navigation'
    name: "navigayion"
    editor:
      preview: false
    files:
      - label: "Footer"
        name: "footer_navigation"
        file: "src/_data/footer_navigation.yaml"
        fields:
          - label: Footer Links
            name: footer_links
            widget: list
            allow_add: true
            collapsed: false
            fields:
              - { label: Label, name: label, widget: string }
              - { label: Url, name: url, widget: string }
      - label: "Header"
        name: "header_navigation"
        file: "src/_data/header_navigation.yaml"
        fields:
          - label: Header Links
            name: header_links
            widget: list
            allow_add: true
            collapsed: false
            fields:
              - { label: Label, name: label, widget: string }
              - { label: Url, name: url, widget: string }
              - label: Second Links
                name: second_links
                widget: list
                allow_add: true
                collapsed: false
                fields:
                  - { label: Label, name: label, widget: string }
                  - { label: Url, name: url, widget: string }
                  - label: Third Links
                    name: third_links
                    widget: list
                    allow_add: true
                    collapsed: false
                    fields:
                      - { label: Label, name: label, widget: string }
                      - { label: Url, name: url, widget: string }
                      - label: Fourth Links
                        name: fourth_links
                        widget: list
                        allow_add: true
                        collapsed: false
                        fields:
                          - { label: Label, name: label, widget: string }
                          - { label: Url, name: url, widget: string }